name: apple_shop
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.3.1
  flutter_lints: ^2.0.2
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  dotted_line: ^3.1.0
  dartz: ^0.10.1
  dio: ^5.2.1+1
  get_it: ^7.6.0
  shared_preferences: ^2.2.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  cached_network_image: ^3.2.3
  persian_number_utility: ^1.1.3
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: GR
      fonts:
        - asset: assets/fonts/GilroyRegular.ttf
    - family: GM
      fonts:
        - asset: assets/fonts/GilroyMedium.ttf
    - family: GB
      fonts:
        - asset: assets/fonts/GilroyBold.ttf
    - family: GEB
      fonts:
        - asset: assets/fonts/GilroyExtraBold.ttf
    - family: GH
      fonts:
        - asset: assets/fonts/GilroyHeavy.ttf
    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
    - family: SB
      fonts:
        - asset: assets/fonts/ShabnamBold.ttf
